POST http://localhost:4000/users/register
Content-Type: application/json

{
    "username" : "test",
    "email" :"test@gmail.com",
    "password" : "123123"
}

###

POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "test@gmail.com",
    "password" : "123123"
}

###


GET http://localhost:4000/users/getFolders/6497fd2092b854ca733ed67a
Content-Type: application/json



###


GET http://localhost:4000/folders/getCards/649842d4f8de2995c9fba224
Content-Type: application/json



###

POST http://localhost:4000/folders/add
Content-Type: application/json

{
    "userId" : "6497fd2092b854ca733ed67a",
    "title" : "testFolder1",
    "description" : "testtestest"

}

###


PUT http://localhost:4000/folders/update
Content-Type: application/json

{
    "folderId" : "649804502dff565bd4be486d",
    "newTitle" : "updatedTestFolder",
    "newDescription" : "updated test description..."

}

###


POST http://localhost:4000/cards/add
Content-Type: application/json

{
    "folderId" : "649842d4f8de2995c9fba224",
    "word" : "test3",
    "meaning" : "test"

}

###


PUT http://localhost:4000/folders/update
Content-Type: application/json

{
    "folderId" : "649804502dff565bd4be486d",
    "cardId" : "64980f475b99acf24d95eec0",
    "newWord" : "UpdatedWord",
    "newMeaning" : "UpdatedMeaning"

}

###

DELETE  http://localhost:4000/folders/remove/6498335386d20ec23c2a4736
Content-Type: application/json              


###


DELETE  http://localhost:4000/cards/remove/6498449bd04db105c4101335
Content-Type: application/json    

###
